version: "3.8"
services:
  frontend-react-js:
    build: ./frontend-react-js/dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      REACT_APP_AWS_USER_POOLS_ID: "us-east-1_kYkxPUvLB"
      REACT_APP_CLIENT_ID: "4ajsh6p2ohuoglvoomq59cnm3c"

  backend-flask:
    volumes:
      - ./backend-flask:/backend-flask
    environment:
      AWS_ENDPOINT_URL: "http://dynamodb-local:8000"
      CONNECTION_URL: "postgresql://postgres:password@db:5432/cruddur"
      FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      AWS_XRAY_URL: "*4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}*"
      AWS_COGNITO_USER_POOL_ID: "us-east-1_kYkxPUvLB"
      AWS_COGNITO_USER_POOL_CLIENT_ID: "4ajsh6p2ohuoglvoomq59cnm3c"

  dynamodb-local:
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  xray-daemon:
    image: "amazon/aws-xray-daemon"

volumes:
  db:
    driver: local
